import { Header } from './components/Header'
import { Sidebar } from './components/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Amazon Web Scrapper',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex bg-[#F7FBFF] h-screen`}>
        <Sidebar/>
        <main className='p-10 max-w-7xl w-full'>
        {/* Header */}
        <Header/>
        {children}
        </main>
        </body>
    </html>
  )
}
